spring:
  application:
    name: posts
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_security
    username: postgres
    password: 0000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

token:
  signing:
    key: "35556d5b5a6156456d384f2d263830754479256424413c5d59663d743f"